added models (Film, User) and their controllers
hbashift/java-filmorate pull request #2
Opened 2023-04-24 09:35 UTC by hbashift

Реализована валидация моделей с помощью javax.validation.constraints + кастомные исключения.

2023-04-24 09:53 UTC, hbashift commented
Нужно ли добавлять свои собственные тесты? Или же это будет лишним?

2023-04-25 05:51 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-04-25 05:51 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/Service.java
> +public interface Service<T> {
лучше переименовать, например, CommonService.

2023-04-25 05:51 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@org.springframework.stereotype.Service
после того как поправить коммент в Service.java, здесь сделайте @Service

2023-04-25 05:51 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +@org.springframework.stereotype.Service
после того как поправить коммент в Service.java, здесь сделайте @Service

2023-04-25 05:51 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film create(@Valid Film film) throws FilmAlreadyExistsException {
здесь @Valid не нужен, вы уже обрабатываете его в контроллере

2023-04-25 05:51 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film update(@Valid Film film) throws NoSuchFilmException {
здесь @Valid не нужен, вы уже обрабатываете его в контроллере

2023-04-25 05:51 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film newFilm(final @Valid @RequestBody Film film) throws FilmAlreadyExistsException {
из контроллеров уберите throws SomeException. вместо этого предлагаю вам попробовать ExceptionHandler.
загуглите Spring boot ExceptionHandler @ControllerAdvice

2023-04-25 05:51 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film newFilm(final @Valid @RequestBody Film film) throws FilmAlreadyExistsException {
в контроллере стирайте только вызывать методы из сервисов, а в сервисах уже обрабатывайте все возможные исключения

2023-04-25 05:51 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @PositiveDuration
хорошо, сделали свою аннотацию, но уже есть @Min(size=0)- вроде так

2023-04-25 06:06 UTC, hbashift commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @PositiveDuration
Нашел. Как лучше сделать? Свою реализацию оставить или воспользоваться существующей?

2023-04-25 06:09 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @PositiveDuration
лучше всегда использовать уже готовое. Если нет то что решает ваши требования или существующая реализация им не удовлетворяет, но можно делать свою

2023-04-25 06:12 UTC, hbashift commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @PositiveDuration
Понял

2023-04-25 07:02 UTC, hbashift commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film newFilm(final @Valid @RequestBody Film film) throws FilmAlreadyExistsException {
Вопрос по иерархии классов. У меня есть два абстрактных класса исключений (AlreadyExists и NoSuchModel). Это в целом приемлемая практика? Или же лучше так не делать?

2023-04-25 08:46 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film newFilm(final @Valid @RequestBody Film film) throws FilmAlreadyExistsException {
кастомные исключение лучше делать, наследуясь от RuntimeException. Не надо усложнять создавая одно исключения, потом исключение, наследующееся от первого и т.д.

2023-04-25 08:49 UTC, ErkinKasymaliev approved these changes
привет, работа принята.
ТОлько к следующей работе поправь последние комменты

2023-04-25 08:49 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/util/exception/AlreadyExistsException.java
> +public abstract class AlreadyExistsException extends IllegalArgumentException {
не надо делать абстрактным, просто наследуйтесь от Runtimeexception

2023-04-25 08:49 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/util/exception/FilmAlreadyExistsException.java
> +public class FilmAlreadyExistsException extends AlreadyExistsException {
не надо наследовать. просто AlreadyExistsException используйте везде где юзер/фильм уже созданы

2023-04-25 08:49 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/util/exception/NoSuchModelException.java
> +public abstract class NoSuchModelException extends NoSuchElementException {
не надо наследовать. просто NoSuchModelException используйте везде где юзер/фильм не найдены

2023-04-25 08:50 UTC, hbashift commented on src/main/java/ru/yandex/practicum/filmorate/util/exception/NoSuchModelException.java
> +public abstract class NoSuchModelException extends NoSuchElementException {
Ок!
Тогда подправлю комменты и сделаю мерж

2023-04-25 09:13 UTC, merged